version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      LIGHTNING_THEME_NAME: Lightning
    volumes:
      - .:/var/www/Lightning
    depends_on:
      - db
    command: "/opt/vendor/bin/phpunit"
